name: Workflow containing a custom action 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - name: checkout code
      uses: actions/checkout@v2

    - name: custom action
      uses: anees12369/CI-CD-Custom-Actions@main
      with: 
        who-to-greet: 'Anees'
        # name on input + an input (my name)




