name: Workflow which contains a secret

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: use secret
      run: echo "The secret is ${{ secrets.MY_FIRST_SECRET }}"
      # This will echo the secret but not actually show it

    - name: using a secret as an env var
      run: echo "The secret is $MY_FIRST_SECRET"
      env:
        MY_FIRST_SECRET: ${{ secrets.MY_FIRST_SECRET }}
      # This will echo the value of $MY_FIRST_SECRET but not show it